FROM ubuntu:22py

ARG TZ='Asia/Shanghai'
ENV BUILD_PREFIX=/app
# ADD ../requirements.txt ${BUILD_PREFIX}

# RUN apt-get update \
#     && cd ${BUILD_PREFIX} \
#     && pip install --no-cache -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple 
